[project]
name = "format-kit"
version = "0.4.0"
requires-python = ">=3.8"
dependencies = ["style-profile @ https://github.com/Millstone123/style-profiles-data/releases/download/v5.0.0/style_profile-5.0.0-py3-none-any.whl"]
[project.scripts]
format-kit = "format_kit.formatter:format_text"
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
